import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import GradientCursor from "@/components/GradientCursor";
import ScrollToTop from "@/components/ScrollTotop";
import PageLoader from "@/components/PageLoader";

const jetBrainMono = JetBrains_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainMono.variable} ${jetBrainMono.variable} antialiased`}
      >
        <PageLoader />
        <GradientCursor />
        <Header />
        {children}
        {/* <Footer /> */}
        <ScrollToTop />
      </body>
    </html>
  );
}
